# All facts below come from the user's brief, the Transwayz product doc, or the live App Store listings (Oct 2026).
PROJECTS = [
# Code Claw facts come from the product website (codeclaw-markting.iapplabz.co.in) as supplied by the owner, Oct 2026.
 dict(slug="code-claw", niche="Developer tools", name="Code Claw", color="#86198F", kind="desktop", ai=True,
  card_img=("assets/code-claw/features.webp","",1600,846),
  hero=("assets/code-claw/hero.webp","The Code Claw website: an AI coding agent on your own machine, with a Download free button for version 0.1.0 on macOS, Windows and Linux",956,778),
  wide=[("assets/code-claw/features.webp","Everything in one desktop app: editor, agent, model choice, git safety and a real dev environment","Code Claw feature overview with five panels: Editor and IDE, An agent that acts, Your models your rules, Git and safety, and Real dev environment",1600,846),
        ("assets/code-claw/god-mode.webp","God Mode: a team of AI agents on one big task, each with a budget and a review step","Code Claw God Mode panel: a team of AI agents on one big task, a budget and review step per subtask, roles from CEO to specialists, and a live task board",1600,296)],
  category="AI coding agent", platform="Desktop app for macOS, Windows and Linux",
  oneliner="A full IDE with an AI agent that reads, writes and runs your code, while your code never leaves your machine.",
  summary="Code Claw is a desktop coding agent for real developers. It builds, debugs and ships local projects using a free local model, a private model or your own API key, with a full editor, terminal and git built in.",
  stats=[("3","desktop platforms"),("20+","programming languages"),("40+","frameworks supported"),("$0","with the free local model")],
  card_stat=("AI coding agent", "Runs on your own machine"),
  brief="Developers want an AI agent that can do real work across a whole project, but many cannot send their code to a third-party cloud, and per-token bills add up fast on long tasks. The goal was a desktop app that pairs a proper IDE with an agent that acts end to end, runs on the developer's own machine, and lets them choose any model, from a free offline one to the frontier models they already pay for.",
  client="Professional developers, freelancers and teams who want AI help on real projects while keeping their code private and their costs under control.",
  hard=[
   ("Private by default","Code had to stay on the developer's machine, so the editor, agent and a local model all needed to work fully offline."),
   ("Any model, one experience","Free local models, frontier models and open models behave differently. Switching between them had to be a one-click choice per conversation."),
   ("An agent you can trust with your repo","An agent that edits and runs code needs guard rails: every change reviewable, every task undoable, and nothing committed by surprise."),
   ("Big jobs, not just snippets","Large tasks had to be split up and coordinated without losing track of cost or quality."),
  ],
  built=[
   ("Editor and IDE","A full, self-hosted code editor with file tree, tabs, project-wide search, syntax highlighting for 20+ languages and an integrated terminal. The editor can be hidden for a clean AI workspace."),
   ("An agent that acts","Reads, writes and runs code end to end, with Build, Plan and Ask modes, up to three conversations at once, slash commands, @-file mentions and screenshot input so it can see your UI."),
   ("Your models, your rules","A free local model through Ollama that runs offline at no cost, bring-your-own keys for Anthropic, Gemini and OpenAI, and open models such as Kimi, DeepSeek and GLM. Switch per conversation."),
   ("Git and safety","Full git (status, branches, commit, push, pull and diffs), accept or reject every change file by file, and an automatic snapshot before each task for one-click undo."),
   ("Real dev environment","Support for 40+ frameworks, project scaffolding for React, Vue, Next and Laravel, dev servers and builds run in-app, and live cost tracking per session."),
   ("God Mode","A team of AI agents on one big task, with roles from CEO down to specialists, a budget and review step for each subtask, and a live task board to watch progress."),
  ],
  how=[
   ("Start with the IDE","We built a complete editor and terminal first, so the agent works inside a real development environment rather than a chat window."),
   ("Make the model a choice","A model layer lets developers move between a free local model, their own API keys and open models without changing how they work."),
   ("Put safety around the agent","Snapshots, per-file review and full git came before autonomy, so developers stay in control of every change."),
   ("Scale up to teams of agents","God Mode coordinates several specialist agents on one task, each with its own budget and review step."),
  ],
  outcome="Version 0.1.0 is out as a free download for macOS, Windows and Linux: an AI coding agent that works on real projects, runs on the developer's own machine and keeps their code private.",
  platforms=["macOS","Windows","Linux","Works offline","Bring your own model"],
  links=[("Visit the Code Claw site","https://codeclaw-markting.iapplabz.co.in/")]),

# GhostAI facts come from meetghostai.com and its help centre (via web search) and the owner's screenshots, Oct 2026.
 dict(slug="ghostai", niche="Meetings and calls", name="GhostAI", color="#3E4A89", kind="ghost", ai=True,
  category="AI meeting assistant", platform="Mac app",
  oneliner="An invisible sidekick that gives you instant answers in meetings, calls and conversations, without anyone knowing.",
  summary="GhostAI is a real-time AI assistant for the Mac. It listens to the call, suggests answers as the conversation happens, takes notes, and turns every meeting into a summary with key points and action items.",
  stats=[("3","meeting apps supported"),("2","Mac builds: Apple Silicon and Intel"),("Live","answers during the call"),("Synced","summaries on all your devices")],
  card_stat=("AI meeting assistant", "Live answers on Zoom, Meet, Teams"),
  brief="In a live call there is no time to search for a fact, check a number or write things down. The goal was an assistant that keeps up with the conversation itself: one that listens, answers the moment a question comes up, stays out of sight when the screen is shared, and leaves a clean record of what was agreed.",
  client="Professionals who spend their day in calls: sales and client meetings, team stand-ups, interviews and presentations.",
  hard=[
   ("Answers in real time","Suggestions are only useful while the question is still being asked, so listening, understanding and answering had to happen in seconds."),
   ("Private on a shared screen","The assistant has to stay visible to its user but never appear when they share their screen in Zoom, Meet or Teams."),
   ("Works with every call app","People switch between meeting platforms all day, so GhostAI had to work across the major ones rather than inside a single app."),
   ("Nothing lost after the call","Notes, key points and action items had to be captured automatically and be there on every device afterwards."),
  ],
  built=[
   ("Real-time suggestions","GhostAI listens to the conversation and suggests answers and talking points as questions come up."),
   ("Invisible when screen sharing","The assistant window stays private to you and does not show up when you share your screen."),
   ("Automatic notes and summaries","Key points, summaries and action items are captured for every call, with no manual note-taking."),
   ("Conversation memory","GhostAI saves memories of past conversations, so context carries over from one meeting to the next."),
   ("Works with your meetings","Plugs into Zoom, Google Meet and Microsoft Teams calls."),
   ("Native Mac app","Separate downloads for Apple Silicon and Intel Macs, opened from the Ghost icon, with summaries that sync across every device you are logged in on."),
  ],
  how=[
   ("Start from the live moment","We designed around the seconds after a question is asked, keeping the path from hearing to answering as short as possible."),
   ("Stay out of the way","The interface is a small, private overlay that never competes with the call or shows up on a shared screen."),
   ("Capture everything after","Notes, summaries, action items and memories are produced automatically, so the meeting record writes itself."),
   ("Ship for every Mac","Native builds for Apple Silicon and Intel, with sync so summaries follow the user across devices."),
  ],
  outcome="A Mac assistant that answers in real time during Zoom, Meet and Teams calls, stays invisible on a shared screen, and turns every meeting into notes and action items.",
  platforms=["macOS 11+","Apple Silicon","Intel Mac","Zoom, Meet and Teams"],
  links=[("Visit meetghostai.com","https://meetghostai.com/")]),

# GenZpark facts come from genzpark.ai (via web search) and the owner's screenshots, Oct 2026.
 dict(slug="genzpark", niche="Content creation", name="GenZpark", color="#3F6212", kind="workspace", ai=True,
  category="AI workspace", platform="Web platform",
  oneliner="An all-in-one AI platform to create, chat, generate and automate faster, from a single dashboard.",
  summary="GenZpark brings powerful AI tools into one simple dashboard. People generate images, create videos, write content, edit documents, build presentations, make music and chat with AI models, all from a single platform and a single account.",
  stats=[("8","AI tool categories"),("50","free credits to start"),("3-day","free trial"),("1","dashboard for everything")],
  card_stat=("All-in-one AI workspace", "8 AI tools, one dashboard"),
  brief="Creators and small teams were paying for a separate AI subscription for every job: one for images, another for video, another for slides, another for writing. The goal was one AI workspace where every workflow stays connected, from the first prompt to the final export, with simple pricing and a way to try it without any commitment.",
  client="Creators, marketers, students and small teams who use AI every day for content, design and documents.",
  hard=[
   ("Eight tools that feel like one","Chat, images, video, documents, slides, music, PDFs and design each have their own workflow, but all had to share one dashboard, one account and one set of projects."),
   ("Costs people can predict","Generating a video costs far more than a chat message. A credit system had to make that clear before anything is created."),
   ("Try first, sign up later","Visitors had to be able to try the product straight away, with no sign-up needed and free credits to start."),
  ],
  built=[
   ("AI chat","Chat with AI models, with unlimited chat messages on the free plan."),
   ("Images and design","Create AI images, AI designs and posters from a prompt, then refine them in a powerful built-in editor."),
   ("AI video","Generate videos from a description without leaving the dashboard."),
   ("Documents and PDFs","Write and edit documents with AI, and chat with PDFs to pull out what matters."),
   ("Slides and presentations","Turn a prompt into a presentation with AI Slides."),
   ("Music","Generate original music tracks for content and projects."),
   ("Credits and plans","A credit cost shown before every generation, 50 free credits to start, and Free, Starter, Creator and Pro plans that refill monthly."),
  ],
  how=[
   ("One dashboard first","We designed the shared workspace before the tools, so every new AI tool plugs into the same projects and files."),
   ("Connect the workflow","From the first prompt to the final export, work moves between tools instead of being downloaded and re-uploaded."),
   ("Make pricing visible","Credits and their cost are shown up front, so people always know what a generation will use."),
   ("Lower the barrier","A three-day free trial, no sign-up to try and free credits let people see the value before they pay."),
  ],
  outcome="One AI workspace that replaces a stack of separate subscriptions: eight AI tool categories, connected projects and clear credit-based pricing, from a free plan up to Pro.",
  platforms=["Web app","Free, Starter, Creator and Pro plans","Credit-based pricing"],
  links=[("Visit genzpark.ai","https://genzpark.ai/")]),

 dict(slug="poster-maker", niche="Graphic design", name="Poster Maker", color="#AE1757", kind="poster", ai=True,
  icon="assets/poster-maker/icon.webp",
  shots=[("assets/poster-maker/screen-1.webp","20,000+ templates for every occasion","Template library filtered by Birthday, Business, Party and Flyer"),
         ("assets/poster-maker/screen-2.webp","Ads that sell, built in minutes","A real-estate ad being designed with brand colours, graphics and shapes"),
         ("assets/poster-maker/screen-3.webp","Invitations, edited in place","A grand opening invitation in the editor, with fonts, AI text and colour tools")],
  category="Graphics and design", platform="iPhone, iPad and Mac",
  oneliner="Type an idea, get a poster. Design flyers, logos and social posts in minutes with AI.",
  summary="Poster Maker gives small businesses, students and creators more than 20,000 editable templates and an AI studio that turns a short prompt into a finished design.",
  stats=[("2.83M","downloads"),("4.6","App Store rating"),("20K","App Store ratings"),("20,000+","templates")],
  card_stat=("2.83M downloads", "4.6 from 20K ratings"),
  brief="Most people who need a flyer or an Instagram post are not designers and do not want to learn a pro tool. The app had to get someone from an idea to a polished, on-brand design in minutes.",
  client="Small business owners, marketers, students and influencers.",
  hard=[
   ("Blank-canvas anxiety","An empty editor stops non-designers cold, so every flow needed a strong starting point."),
   ("A huge library that stays fast","Tens of thousands of templates, fonts and assets had to load quickly on any device."),
   ("AI that stays editable","AI output had to land as a normal editable design, not a flat image."),
  ],
  built=[
   ("AI poster generation","Describe it, for example a neon party flyer, and get an editable design."),
   ("20,000+ templates","Posters, flyers, logos, business cards, invitations, banners and social posts."),
   ("Drag-and-drop editor","Change text, swap images, adjust colours, add icons, with 100+ designer fonts."),
   ("AI design tools","Background remover, object eraser, image upscaler, photo colouriser and AI art."),
   ("AI product branding","Product posters and promotional creatives generated in seconds."),
   ("Video and motion","Photo-to-video and a video editor for moving content."),
  ],
  how=[
   ("Start from a template","Every path begins with a strong layout, so users edit rather than invent."),
   ("Layer AI into the editor","AI studio, carousel suggestions and history sit alongside the familiar editor."),
   ("Keep it light","Reduced app size, faster template loading and broad iOS support kept older devices in play."),
  ],
  outcome="Close to three million downloads and a 4.6 rating across 20,000 App Store reviews, in 28 languages.",
  platforms=["iPhone","iPad","Mac","Apple Vision","28 languages"],
  links=[("Download on the App Store","https://apps.apple.com/us/app/poster-maker-ai-flyer-design/id1241339881")]),
# 3D demo facts come from the live demo site and the owner's screen recording of it, Oct 2026.
 dict(slug="3d-demo", niche="3D web design", name="3D Creator Site", color="#3D4350", kind="web", demo=True,
  card_img=("assets/3d-demo/hero.webp","",1200,571),
  hero=("assets/3d-demo/hero.webp","The demo's hero: oversized metallic HI, I'M JACK type behind a 3D cartoon character, with a Contact me button",1200,571),
  wide=[("assets/3d-demo/about.webp","About: floating glass 3D objects and a paragraph that lights up word by word as you scroll","About me section with a glass moon and a glass cube floating either side of the heading, and paragraph text fading in",1600,762),
        ("assets/3d-demo/services.webp","Services: numbered items that fade in one by one on a white panel that slides over the page","Services list on a white panel: 02 Rendering, 03 Motion design and a faded 04 Branding",1600,762),
        ("assets/3d-demo/projects.webp","Projects: cards that pin and stack on top of each other as you scroll","Project section heading above the first stacked project card, 01 Nextlevel Studio, with a Live project button",1600,762)],
  category="3D website demo", platform="Interactive website",
  oneliner="A cinematic 3D portfolio site where the character follows your cursor and every section moves with your scroll.",
  summary="A dark, cinematic portfolio for a fictional 3D creator, built by iApp Technologies to show what a 3D-first website can feel like: a character that watches your cursor, sections that reveal as you scroll and project cards that stack into place.",
  stats=[("3D","character that follows your cursor"),("4","services revealed on scroll"),("3","project cards that stack"),("0","plugins or downloads needed")],
  card_stat=("3D web demo", "Cursor and scroll animation"),
  brief="Studios, creators and brands increasingly want websites that feel like products, not brochures. We built this demo to show clients the interactive techniques we use, from real-time 3D to scroll-driven animation and layered depth, all running in an ordinary web browser.",
  client="Brands, studios and creators who want a website people remember, and teams weighing up 3D and motion for their own sites.",
  hard=[
   ("Depth without lag","A 3D character, layered type and animated sections all had to stay smooth while the page scrolls."),
   ("Motion that guides","Every animation had to lead the eye to the next section rather than distract from the content."),
   ("A character with personality","The hero character reacts to the visitor's cursor, so the page feels alive from the first second."),
  ],
  built=[
   ("Interactive 3D hero","A 3D character whose head and eyes follow the cursor, set in front of oversized metallic type."),
   ("Scrolling showcase","A wall of project screenshots that glides sideways as the visitor scrolls."),
   ("Scroll-revealed story","An About section with floating glass 3D objects and a paragraph that lights up word by word."),
   ("Services that unfold","Numbered services (3D modelling, rendering, motion design and branding) fade in one by one on a white panel that slides over the page."),
   ("Stacking project cards","Project cards pin and stack on top of each other as you scroll, each with a Live project link."),
   ("Runs in the browser","No plugins or downloads: the whole experience loads like any other website."),
  ],
  how=[
   ("Design the first five seconds","The hero had to make an impression before anyone scrolls, so the character and type were designed together."),
   ("Choreograph the scroll","Each section has one clear motion idea, timed to the visitor's scroll rather than a fixed clock."),
   ("Tune for smoothness","Animations were kept to the browser's fastest paths so the page stays fluid while it moves."),
   ("Make it reusable","The same techniques carry over to product launches, studio portfolios and SaaS landing pages."),
  ],
  outcome="A live demo clients can open in their browser to feel what a 3D, motion-led website could do for their brand.",
  platforms=["Web browser","Cursor and scroll animation","Hosted on Vercel"],
  links=[("View the live demo","https://demo-3d-iapp-technologies.vercel.app/")]),
 dict(slug="transwayz", niche="Trucking and logistics", name="Transwayz", color="#1A30D2", kind="web",
  hero=("assets/transwayz/dispatch.webp","Transwayz trips and dispatch board showing active orders, trips in progress, available drivers and five live trips with their status",695,784),
  wide=[("assets/transwayz/integrations.webp","Integrations: accounting, fuel tax (IFTA), telematics and EDI connectors, each configured in-app","Transwayz integrations screen listing accounting, IFTA and telematics connectors next to the module list with screen counts",1600,573)],
  flow=[("Capture order","Create a one-off order, set up a recurring one or bulk-import from a spreadsheet. Each order holds the customer, stops, dates, goods and rate.","#3B6CF0","box"),
        ("Dispatch trip","Turn the order into a trip and assign a driver, truck and trailer or an outside carrier, with each driver's remaining driving hours in view.","#1A2238","truck"),
        ("Track and deliver","Follow the truck on the live map. Every status change is time-stamped, and delivery papers and photos are attached to the trip.","#2F9467","pin"),
        ("Invoice and settle","Invoice the customer from the completed trip and run the driver settlement. Recorded payments mark invoices and bills as paid.","#1A2238","receipt")],
  category="Logistics SaaS", platform="Web platform for many companies",
  oneliner="One system for trucking companies to run the whole life of a load, from customer order to driver pay.",
  summary="Transwayz brings orders, dispatch, tracking, invoicing, driver settlements and fuel-tax reporting into one online system. Many trucking companies run on it at the same time, and each one only ever sees its own data.",
  stats=[("10","product modules"),("7","ELD providers connected"),("5","user roles"),("7","tracked trip stages")],
  card_stat=("7 ELD integrations", "Samsara, Motive, Geotab and more"),
  brief="Trucking companies were running their business across phone calls, spreadsheets, accounting tools and separate driving-hours logs. The goal was a single online system that follows a load end to end: a customer asks for a move, the team creates an order, a dispatcher assigns a driver, truck and trailer, the trip is tracked to delivery, and then the customer is invoiced and the driver and partners are paid.",
  client="Built for small and mid-sized carriers and the dispatchers, drivers and accounts teams who work inside them.",
  hard=[
   ("Many companies, one system","Every carrier shares the same platform, so data separation had to be built into the foundation: each company sees only its own customers, trips and money."),
   ("Data from the truck itself","Location and legal driving hours live in electronic logging devices from different vendors. Dispatch needed that data automatically, not re-typed."),
   ("Money in, money out","Customer invoices, driver pay, carrier pay, vendor bills and bank matching all had to close the loop on the same trip record."),
   ("Compliance paperwork","Fuel tax (IFTA) reporting needs miles by state or province, pulled from real trip and fuel data rather than estimates."),
  ],
  built=[
   ("Orders","Multi-stop pickups and deliveries, copy and reverse for return trips, recurring daily or weekly orders, drafts, and bulk import from spreadsheets."),
   ("Trips and dispatch","Assign a driver, truck and trailer or an outside carrier. Every stage is time-stamped, from planned to completed, with documents, photos and a printable trip sheet."),
   ("Live map and driving hours","Trucks on a live map, with each driver's remaining legal hours visible before a load is assigned."),
   ("ELD connections","Location and hours pulled in automatically from Samsara, Motive, Geotab, Omnitracs, PeopleNet, Isaac and Fleet Hunt."),
   ("Accounting","Invoices emailed as PDFs, driver settlements with bonuses and deductions, carrier pay, vendor bills, automatic paid status and bank reconciliation."),
   ("IFTA and reporting","Fuel-tax and mileage reports by state, plus sales, trip profitability, fuel economy and unpaid-invoice ageing with spreadsheet and PDF export."),
   ("Access and audit","Admin approval for new users, five role-based views, and an activity log that records who changed what and when."),
   ("Marketing site and blog","A public website and blog so the Transwayz team can attract and convert new carriers."),
  ],
  how=[
   ("Map the load","We modelled the real business flow first: order, trip, delivery, invoice, settlement, report. Every screen hangs off that chain."),
   ("Design by role","Admin, Dispatcher, Driver, Accounts and Reports each get only the screens they need, which keeps a dense product calm to use."),
   ("Integrate the fleet","ELD providers were connected one by one so trip status and driving hours flow in without manual entry."),
   ("Close the books","Accounting, reconciliation and IFTA were built on the same trip data, so operations and finance never disagree."),
  ],
  outcome="A single place where a carrier can take an order, dispatch it, watch it move, bill for it and pay everyone involved, with reports that show how the business is doing.",
  platforms=["Web app","Multi-tenant","PDF and spreadsheet export","Public website and blog"],
  links=[("Visit transwayz.com","https://transwayz.com/")]),

 dict(slug="baridata", niche="Healthcare", name="Baridata", color="#0F766E", kind="registry",
  card_img=("assets/baridata/dashboard.webp","",1600,498),
  hero=("assets/baridata/hero.webp","Baridata illustration of a patient with BMI and HbA1c falling, an average %TWL card and an outcomes snapshot",652,711),
  wide=[("assets/baridata/dashboard.webp","The outcomes dashboard: average %TWL over 24 months, total cases, diabetes remission and complication rate","Baridata outcomes dashboard with a %TWL curve over 24 months and cards for total cases, average %TWL at 12 months, diabetes remission and major complications",1600,498)],
  category="Healthcare SaaS", platform="Cloud web platform",
  oneliner="A cloud clinical registry that lets bariatric surgeons log a surgery in about two minutes and watch patient outcomes update live.",
  summary="Baridata replaces spreadsheets with one central registry for bariatric surgery. Surgeons capture each case quickly, clinical staff manage follow-ups, dashboards update as data comes in, and anonymised datasets are ready for audits and research.",
  stats=[("2 min","to log a complete surgery"),("44+","bariatric centres across India"),("6","steps from surgery to research export"),("Live","outcomes dashboard")],
  card_stat=("2-minute surgery capture", "Live outcomes dashboard"),
  brief="Bariatric programmes depend on long-term data: weight loss, diabetes remission, nutrition and complications, tracked for years after surgery. That data sat across spreadsheets and separate systems, follow-up visits were missed, and preparing a dataset for a study or an audit took a great deal of manual cleaning. The goal was a single platform that makes capture fast and keeps outcomes visible every day.",
  client="Bariatric surgeons, clinical staff and hospital programmes across India that report on outcomes and publish research.",
  hard=[
   ("Documentation eats surgeon time","Procedures were being recorded across multiple systems and spreadsheets, and every centre recorded them differently."),
   ("Follow-ups slip","Missed visits leave gaps in long-term outcome data, which is exactly the data a bariatric programme is judged on."),
   ("Outcomes arrive weeks late","Without live dashboards, surgeons waited weeks for reports and summaries."),
   ("Research and benchmarking are slow","Datasets needed heavy cleaning before analysis, and hospitals had no easy way to compare their results with peers."),
  ],
  built=[
   ("Digital surgery registry","Patient demographics, procedure details and early outcomes captured in about two minutes."),
   ("Follow-up management","Scheduled visits with reminders and alerts for missed appointments."),
   ("Live outcomes dashboard","%TWL, %EWL, diabetes remission and complication rates, updated as data is entered."),
   ("Per-patient timeline","Weight-loss progress, nutritional markers, HbA1c trends and long-term recovery for each patient."),
   ("National benchmarking","Compare surgeons and hospitals against bariatric procedures nationwide."),
   ("Research-ready export","Anonymised CSV and Excel datasets for audits, clinical studies and publications."),
  ],
  how=[
   ("Design for the operating day","Capture was built to take about two minutes, so surgeons record every case rather than catching up later."),
   ("Make follow-ups automatic","Reminders and missing-visit alerts replace manual tracking."),
   ("Turn records into live metrics","Dashboards and patient timelines update straight from the registry, with no separate reporting step."),
   ("Build for research","Anonymised exports and benchmarking make the same data useful for studies, audits and quality improvement."),
  ],
  flow_title="Inside the product",
  flow_caption="The end-to-end bariatric surgery workflow in Baridata",
  flow=[("Surgery logging","Capture patient demographics, procedure details and early outcomes in about two minutes.","#0F766E","clipboard"),
        ("Follow-up management","Clinical staff record scheduled visits and update recovery milestones.","#1A2238","calendar"),
        ("Live dashboard updates","Outcome metrics refresh automatically as new clinical data is entered.","#3B6CF0","pulse"),
        ("Outcome monitoring","Track weight loss, diabetes remission, nutrition and complications over time.","#1A2238","chart"),
        ("Hospital benchmarking","Compare results across hospitals, surgeons, procedures and patient cohorts.","#2F9467","bars"),
        ("Research export","Generate anonymised datasets for research, quality improvement and reporting.","#1A2238","download")],
  outcome="One registry for the whole bariatric programme: surgeries logged in minutes, follow-ups tracked automatically, outcomes visible live and research data ready when it is needed.",
  platforms=["Cloud web app","Anonymised data","CSV and Excel export"],
  links=[("Visit baridata.com","https://baridata.com/")]),
 dict(slug="beatstars", niche="Music", name="BeatStars", color="#161616", kind="player",
  icon="assets/beatstars/icon.webp",
  shots=[("assets/beatstars/screen-1.webp","A player built for discovering beats","The BeatStars player showing a track with like, comment, follow and add-to-cart controls"),
         ("assets/beatstars/screen-2.webp","Messages between artists and producers","The BeatStars Messages inbox with conversations between producers and artists"),
         ("assets/beatstars/screen-3.webp","Playlists for every project","A BeatStars playlist page with play, follow, share and edit options and playlist stats")],
  wide=[("assets/beatstars/web.webp","The same marketplace on the web: 8 million+ beats, simple licensing and a creator community","BeatStars web page listing the largest beats marketplace, seamless purchasing, simple licensing and community",1200,816)],
  category="Music marketplace", platform="iPhone and Android",
  oneliner="The mobile home of the world's largest beats marketplace, where creators stream, license and collaborate.",
  summary="BeatStars lets artists explore and buy from a catalogue of over 8 million beats, instrumentals, hooks and sound kits, and connects them with the producers who made them.",
  stats=[("1M+","downloads"),("4.8","App Store rating"),("80K","App Store ratings"),("8M+","beats in the catalogue")],
  card_stat=("4.8 from 80K ratings", "1M+ downloads"),
  brief="BeatStars serves a community of more than 10 million creators. The mobile app had to make a catalogue of millions of tracks feel personal, make licensing a studio-ready beat take a few taps, and give artists and producers a way to find each other.",
  client="Artists, songwriters, producers and engineers, from hobbyists to working professionals.",
  hard=[
   ("Discovery at catalogue scale","With 8 million+ tracks, search alone is not enough. The feed has to learn what each creator likes and keep surfacing fresh sound."),
   ("Licensing without friction","Buying a beat means picking a licence and getting files that drop straight into a DAW. That flow had to be fast and unambiguous on a phone."),
   ("Playback that never drifts","Continuous streaming, a mini player, ads and track skipping all have to stay in sync with what is on screen."),
  ],
  built=[
   ("Personalised feed","Curated playlists and recommendations that sharpen the more a creator streams."),
   ("Marketplace checkout","Simple licence options and studio-ready downloads that work with Pro Tools, FL Studio, Ableton and Cubase."),
   ("Lyric pad and playlists","Write lyrics, search rhymes and organise upcoming projects in unlimited playlists."),
   ("Follow and message","Follow producers, songwriters and engineers, message them and share ideas."),
   ("Creator profiles","Profiles with tracks, sound kits, collections, sorting, filtering and bulk deals."),
   ("Free downloads with terms","Zero-dollar licences with built-in commercial terms and revenue share."),
  ],
  how=[
   ("Listen first","The player is the heart of the app, so playback reliability and sync were treated as core engineering, not polish."),
   ("Shorten the path to a licence","We reduced the steps from hearing a beat to owning the files."),
   ("Ship continuously","Frequent releases tuned recommendations, profiles and checkout based on how creators actually used them."),
  ],
  outcome="A top-rated music app that holds a 4.8 average across 80,000 App Store ratings and has passed one million downloads.",
  platforms=["iPhone","Android","Apple Vision","6 languages"],
  links=[("Download on the App Store","https://apps.apple.com/us/app/beatstars-instrumental-beats/id1436154382"),("Get it on Google Play","https://play.google.com/store/apps/details?id=com.beatstars.mobile"),("Visit beatstars.com","https://www.beatstars.com/")]),

 dict(slug="pdf-converter", name="PDF Converter", color="#C2261C", kind="pdf",
  icon="assets/pdf-converter/icon.webp",
  shots=[("assets/pdf-converter/screen-1.webp","Every PDF tool on one home screen","The PDF Converter home screen with tools for creating PDFs, PDF to Word, scanning, cloud, invoices, CV maker and recent files"),
         ("assets/pdf-converter/screen-2.webp","Scan paper into PDF, Word, Excel and more","A business letter being scanned with the camera, with PDF, Word, PowerPoint, Excel and ePub export options"),
         ("assets/pdf-converter/screen-3.webp","Fill forms and sign on the phone","An admission form filled in and signed in the editor, with Add Page, OCR, Sign and Smudge tools")],
  category="Productivity", platform="iPhone, iPad and Mac",
  oneliner="A complete PDF toolkit in your pocket: convert, edit, sign and organise any document.",
  summary="PDF Converter turns photos, Word, PowerPoint, Excel and web pages into PDFs and back again, with a full editor, e-signatures and an AI assistant built in.",
  stats=[("4.99M","downloads"),("4.4","App Store rating"),("6K","App Store ratings"),("25","languages")],
  card_stat=("4.99M downloads", "4.4 rating, 25 languages"),
  brief="People handle documents on their phones all day, but converting, merging or signing a PDF usually means a desktop. The app needed to put every common PDF task one tap away, work with the files people already keep in the cloud, and stay fast as the toolset grew.",
  client="Students, freelancers and office workers who need to get a document done without a laptop.",
  hard=[
   ("Dozens of tools, one simple home","Merge, split, compress, convert, sign, annotate and more had to stay discoverable without turning the home screen into a maze."),
   ("Conversions that just work","Word, PowerPoint, Excel, HTML and image formats each have quirks; output had to be reliable and quick."),
   ("Files live everywhere","Documents sit in Drive, Dropbox, OneDrive, Box, SharePoint, Files and Mail. The app had to meet them there."),
  ],
  built=[
   ("Convert both ways","JPG, Word, PowerPoint, Excel and HTML to PDF, and PDF back to JPG, Word, PowerPoint and Excel."),
   ("Organise PDFs","Merge, split, compress, rotate, unlock and watermark."),
   ("Editor and annotation","Text, shapes, highlights, sticky notes and freehand drawing, plus a distraction-free reader mode."),
   ("Forms and signatures","Fill PDF forms and add, edit or remove digital signatures."),
   ("Cloud and security","Import from and upload to the major cloud drives, with password protection and encryption."),
   ("AI assistant","AI summaries, OCR and an assistant that finds the right tool, plus search inside file contents."),
  ],
  how=[
   ("Lead with intent","A smarter landing screen asks what you came to do and routes you straight to the right tool."),
   ("Grow the toolkit","New modules such as invoice and CV makers, a text editor, Excel editor and scroll-shot capture were added without crowding the core."),
   ("Go global","Localised into 25 languages and extended to iPad, Mac and Apple Vision."),
  ],
  outcome="Nearly five million downloads and a 4.4 rating across more than 6,000 App Store reviews.",
  platforms=["iPhone","iPad","Mac","Apple Vision","25 languages"],
  links=[("Download on the App Store","https://apps.apple.com/us/app/pdf-converter-pdf-editor/id684119875")]),

 dict(slug="screen-recorder", name="Screen Recorder", color="#C2410C", kind="rec",
  icon="assets/screen-recorder/icon.webp",
  shots=[("assets/screen-recorder/screen-1.webp","Face cam reactions over gameplay","A mobile game being recorded with a face-cam reaction bubble and recording controls"),
         ("assets/screen-recorder/screen-2.webp","A full editor on the timeline","The video editor with gameplay, face-cam and audio tracks on a timeline, plus text, sticker and music tools"),
         ("assets/screen-recorder/screen-3.webp","One tap to record anything","The iOS Screen Broadcast panel with Screen Recorder selected and ready to start")],
  category="Utilities", platform="iPhone, iPad and Mac",
  oneliner="Record, react, edit and stream your screen from one app.",
  summary="Screen Recorder captures games, tutorials, calls and live shows in HD, adds a face-cam reaction and voice commentary, and edits the result before it goes to YouTube, Facebook or Twitch.",
  stats=[("3.06M","downloads"),("4.6","App Store rating"),("2.8K","App Store ratings"),("9","languages")],
  card_stat=("3.06M downloads", "4.6 rating"),
  brief="Creators record on the phone but have to jump between apps to add commentary, trim and publish. The brief was one app that covers the whole loop: capture, react, edit and share.",
  client="Gamers, educators and creators making tutorials, demos and reaction videos.",
  hard=[
   ("Recording without lag","Capture has to stay smooth while a game or video is running, and start or stop from a floating control."),
   ("Reaction on top of content","Face-cam and voice commentary must line up with the recording and be adjustable clip by clip."),
   ("Editing on a small screen","Trimming, merging, music, text, speed and transitions needed to fit comfortably on a phone."),
  ],
  built=[
   ("One-tap recording","Start and stop from the notification bar or a floating window, with external audio."),
   ("Live streaming","Stream your screen to YouTube, Facebook and Twitch."),
   ("Reaction camera","Face-cam overlay and real-time voice commentary on any video, web page or photo."),
   ("Video editor","Trim, merge, add music, text and subtitles, stickers, watermarks, filters, speed changes, crop and transitions."),
   ("Long screenshots","Stitch photos or generate long screenshots straight from a recording."),
   ("AI video module","Smart editing and automatic improvements to recordings."),
  ],
  how=[
   ("Protect the capture","Performance and stability came first, with recurring work on recording smoothness and crash fixes."),
   ("Make reactions first-class","The reaction camera and commentary were rebuilt as their own module."),
   ("Localise and refresh","A modern UI refresh and localisation into nine languages widened the audience."),
  ],
  outcome="More than three million downloads and a 4.6 average rating on the App Store.",
  platforms=["iPhone","iPad","Mac","Apple Vision","9 languages"],
  links=[("Download on the App Store","https://apps.apple.com/us/app/screen-recorder/id1578839671")]),

 dict(slug="singles-connect", niche="Dating app", name="Singles Connect", color="#6D2FD6", kind="dating",
  category="Dating app", platform="iPhone and Android",
  oneliner="A Canadian dating app built around verified profiles, real conversations and face-to-face video calls.",
  summary="Singles Connect is a swipe-based dating and geosocial app. Members browse nearby profiles, swipe to like or pass, match, then chat with photo sharing and meet over in-app voice and video calls.",
  stats=[("5K+","downloads on Google Play"),("4.5","Google Play rating"),("15","App Store releases"),("2024","launched in January")],
  card_stat=("4.5 on Google Play", "5K+ downloads"),
  shots=[("assets/singles-connect/screen-1.webp","Swipe through people nearby","The Singles Connect home screen with a stack of profile cards and like, pass and super-like buttons"),
         ("assets/singles-connect/screen-2.webp","Video calls inside the app","An in-app video call between two matches with camera, mute and end-call controls"),
         ("assets/singles-connect/screen-3.webp","Matches that start with shared interests","The match screen showing two connected profiles and the interests they share, with a Say HI button"),
         ("assets/singles-connect/screen-4.webp","Profiles that show who someone is","A verified profile with photos, distance, occupation, height and interests")],
  brief="The client, Singles Connect 2022 Inc. of Hay Lakes, Alberta, is a relationship-focused company that also runs matchmaking, workshops and community events for singles. They needed an app that carries that approach onto phones: real people, safe conversations, and an easy path from a match to an actual conversation.",
  client="Singles in Alberta, across Canada and beyond who are looking for real relationships.",
  hard=[
   ("Trust from the first swipe","Fake profiles sink dating apps. Verification had to be strong enough to matter and simple enough that people actually complete it."),
   ("Real time, every time","Chat, photo sharing and voice and video calls all had to feel instant on both iOS and Android."),
   ("Close, but not too close","People want to know who is nearby without anyone seeing their exact location, so distance is shown as an approximation."),
   ("Paid plans without friction","Auto-renewing subscriptions had to work cleanly through both app stores, with clear terms."),
  ],
  built=[
   ("Swipe and match","Swipe right to like, left to pass, or send a super-like. Mutual likes become a match."),
   ("Rich profiles","Photos, a short bio, occupation, height, interests and approximate distance."),
   ("Face verification","Members verify with their face, so matches know the profile is genuine."),
   ("Chat with photo sharing","Real-time messaging with pictures, opened straight from a match."),
   ("Voice and video calls","Meet face to face inside the app before meeting in person."),
   ("Subscriptions","Monthly, three-month and six-month auto-renewing plans through the App Store and Google Play."),
  ],
  how=[
   ("Launch the core","Version 1.0 shipped in January 2024 with swiping, matching and chat."),
   ("Listen and adjust","Releases replaced phone verification with email sign-in, removed swipe limits, added picture sharing in chat and a new profile design."),
   ("Build trust","Face verification and verified badges arrived to keep the community genuine."),
   ("Polish and speed up","Later versions brought in-app calling, smoother swiping and faster loading, through version 5.0 in September 2026."),
  ],
  outcome="Fifteen App Store releases since January 2024 and a 4.5 rating on Google Play, with swiping, verification, chat and video calls covered end to end.",
  platforms=["iPhone","Android","English"],
  links=[("Download on the App Store","https://apps.apple.com/in/app/singles-connect/id6466390560"),("Get it on Google Play","https://play.google.com/store/apps/details?id=com.single.connect.app.dating&hl=en_IN"),("Visit singlesconnect.ca","https://singlesconnect.ca/")]),
]
